name: raqamlar
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Translations
  sprintf: ^7.0.0

  #bloc
  bloc: ^8.1.2

  #ROUTING
  auto_route: ^8.1.2

  #UI
  flutter_svg: ^2.0.7
  photo_view: ^0.15.0
  cached_network_image: ^3.2.3
  #intl_phone_field: ^3.2.0
  flutter_styled_toast: ^2.1.3
  syncfusion_flutter_charts: ^25.1.41+1
  flutter_cupertino_datetime_picker: ^3.0.0
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.4
  flutter_staggered_grid_view: ^0.7.0


  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0

  #NETWORK
  dio: ^5.3.2
  connectivity_plus: ^6.0.3

  #retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  #DB
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1


  #Freezed
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  #Functional dart
  dartz: ^0.10.1
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  locale_gen: ^12.0.0
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^3.0.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/logo.png"


flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/svg/
